import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TrpcProvider from "./_trpc/TrpcProvider";
import AuthProvider from "./_context/AuthProvider";
import goku from '../../public/goku.png'
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <TrpcProvider>
            <header className="hidden md:block bg-gray-700 p-4 pl-20 mt-3">
              <h1 className="text-gray-100">Javier Bravo Zapico</h1>
              <h2 className="text-gray-100">Front-end Developer</h2> 
              <nav>
              <Link href='/'><li className="text-gray-100">Home -</li></Link>
                <Link href='/latest'><li className="text-gray-100">Latest Project -</li></Link>
                <Link href='/contact'><li className="text-gray-100">Contact</li> </Link>
              </nav> 
            </header>
            <header className="block md:hidden bg-gray-700 p-4 pl-20 mt-3">
              <h1 className="text-gray-100">Javier Bravo Zapico</h1>
              <h2 className="text-gray-100">Frontend Developer</h2> 
              <nav className="mobile-nav">
              <Link href='/'><li className="text-gray-100">Home -</li></Link>
                <Link href='/latest'><li className="text-gray-100">Latest Project -</li></Link>
                <Link href='/contact'><li className="text-gray-100">Contact</li> </Link>
              </nav> 
            </header>
            {children}
            <footer className="hidden md:block">
              <Image className="goku hidden md:block" src={goku} width={300} height={100} alt="" />
              <h3 className="footer-text">Sleep, code, eat...</h3>
            </footer>
            <footer className="footer-mobile block md:bhidden">
              <Image className="goku-mobile block md:hidden" src={goku} width={300} height={100} alt="" />
              <h3 className="footer-text">Sleep, code, eat...</h3>
            </footer>
            </TrpcProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
